// S7-W39 — accessory fixture catalog.
// 4 categories × 5-7 accessories each. Every entry has real-shape specs
// (quality, price_score, longevity) in [0,1] + a compat spec naming the
// gating rule. URLs stay null to keep the "no affiliate" rule airtight
// until we wire explicit canonical-retailer lookups.

import type { AccessoryFixture } from "./types.js";

const ESPRESSO: AccessoryFixture[] = [
  {
    name: "54mm Calibrated Tamper",
    brand: "Normcore",
    price: 39.99,
    category: "espresso-machines",
    accessoryKind: "accessory/tamper",
    url: null,
    specs: { quality: 0.85, price_score: 0.75, longevity: 0.95 },
    compatibleWith: { portafilterSize: "54mm" },
    why: "Calibrated spring mechanism delivers consistent 30lb tamp pressure; steel contact surface lasts decades.",
  },
  {
    name: "54mm Silicone Tamper Mat",
    brand: "IKAPE",
    price: 9.99,
    category: "espresso-machines",
    accessoryKind: "accessory/tamper-mat",
    url: null,
    specs: { quality: 0.65, price_score: 0.95, longevity: 0.80 },
    compatibleWith: { portafilterSize: "54mm" },
    why: "Corner cutout holds the 54mm portafilter upright while you tamp.",
  },
  {
    name: "12oz Stainless Milk Pitcher",
    brand: "Rattleware",
    price: 24.95,
    category: "espresso-machines",
    accessoryKind: "accessory/milk-pitcher",
    url: null,
    specs: { quality: 0.90, price_score: 0.60, longevity: 0.95 },
    compatibleWith: {},
    why: "Balanced spout geometry for cappuccino-scale drinks; stainless steel resists dings.",
  },
  {
    name: "Bean-sized Knock Box",
    brand: "Espro",
    price: 44.95,
    category: "espresso-machines",
    accessoryKind: "accessory/knock-box",
    url: null,
    specs: { quality: 0.80, price_score: 0.55, longevity: 0.90 },
    compatibleWith: {},
    why: "Shock-absorbing silicone knock bar; 24-puck capacity handles a week of home use.",
  },
  {
    name: "Full-Citric Descaling Kit",
    brand: "Urnex",
    price: 14.99,
    category: "espresso-machines",
    accessoryKind: "accessory/descaler",
    url: null,
    specs: { quality: 0.75, price_score: 0.85, longevity: 0.50 },
    compatibleWith: { brands: ["Breville", "De'Longhi", "Gaggia", "Rancilio", "Rocket"] },
    why: "Citric-based descaler safe for stainless boilers; one kit = one year of quarterly descales.",
  },
  {
    name: "Breville Claro Swiss Water Filter (2-pack)",
    brand: "Breville",
    price: 12.95,
    category: "espresso-machines",
    accessoryKind: "accessory/water-filter",
    url: null,
    specs: { quality: 0.80, price_score: 0.70, longevity: 0.30 },
    compatibleWith: { brands: ["Breville"] },
    why: "OEM replacement filters — swap every 2 months to keep scale down.",
  },
];

const LAPTOP: AccessoryFixture[] = [
  {
    name: "7-port USB-C Hub",
    brand: "Anker",
    price: 59.99,
    category: "laptops",
    accessoryKind: "accessory/hub",
    url: null,
    specs: { quality: 0.85, price_score: 0.70, longevity: 0.85 },
    compatibleWith: { productTokens: ["usb-c", "thunderbolt", "macbook", "xps", "framework"] },
    why: "PD passthrough + 4K60 HDMI + dual USB-A + card readers covers the common docking set.",
  },
  {
    name: "Adjustable Laptop Stand",
    brand: "Roost",
    price: 89.95,
    category: "laptops",
    accessoryKind: "accessory/stand",
    url: null,
    specs: { quality: 0.95, price_score: 0.45, longevity: 0.95 },
    compatibleWith: {},
    why: "Holds laptops up to 17 inches at ergonomic eye-height; folds flat for travel.",
  },
  {
    name: "NVMe External SSD Enclosure",
    brand: "Sabrent",
    price: 34.99,
    category: "laptops",
    accessoryKind: "accessory/ssd-enclosure",
    url: null,
    specs: { quality: 0.75, price_score: 0.85, longevity: 0.80 },
    compatibleWith: {},
    why: "USB 3.2 Gen2 (10 Gbps) housing for any M.2 NVMe drive; tool-less install.",
  },
  {
    name: "15-inch Padded Laptop Sleeve",
    brand: "Tomtoc",
    price: 19.99,
    category: "laptops",
    accessoryKind: "accessory/sleeve",
    url: null,
    specs: { quality: 0.70, price_score: 0.90, longevity: 0.75 },
    compatibleWith: {},
    why: "CornerArmor shock padding + water-resistant shell; fits most 14-15 inch laptops.",
  },
  {
    name: "6ft HDMI 2.1 Cable",
    brand: "Monoprice",
    price: 14.99,
    category: "laptops",
    accessoryKind: "accessory/cable",
    url: null,
    specs: { quality: 0.85, price_score: 0.95, longevity: 0.90 },
    compatibleWith: {},
    why: "48 Gbps bandwidth supports 4K120 + 8K60 on compatible displays; braided jacket.",
  },
  {
    name: "Laptop Cooling Pad",
    brand: "TopMate",
    price: 29.99,
    category: "laptops",
    accessoryKind: "accessory/cooling-pad",
    url: null,
    specs: { quality: 0.70, price_score: 0.80, longevity: 0.65 },
    compatibleWith: {},
    why: "Five adjustable fans + USB-powered; helps heavy workloads stay out of thermal throttling.",
  },
];

const HEADPHONES: AccessoryFixture[] = [
  {
    name: "Replacement Ear Cushions (Premium Leather)",
    brand: "Brainwavz",
    price: 24.99,
    category: "headphones",
    accessoryKind: "accessory/ear-cushions",
    url: null,
    specs: { quality: 0.80, price_score: 0.80, longevity: 0.65 },
    compatibleWith: { productTokens: ["over-ear", "xm4", "xm5", "wh-1000", "ath-m50", "hd 600"] },
    why: "Memory-foam sheepskin cushions restore seal + comfort on older cans.",
  },
  {
    name: "Hard Travel Case (Headphones)",
    brand: "WgGe",
    price: 16.99,
    category: "headphones",
    accessoryKind: "accessory/case",
    url: null,
    specs: { quality: 0.70, price_score: 0.90, longevity: 0.80 },
    compatibleWith: {},
    why: "Semi-hard EVA shell fits most foldable over-ear headphones; carabiner clip.",
  },
  {
    name: "1.2m Braided 3.5mm TRS Cable",
    brand: "iBasso",
    price: 19.99,
    category: "headphones",
    accessoryKind: "accessory/cable",
    url: null,
    specs: { quality: 0.80, price_score: 0.80, longevity: 0.85 },
    compatibleWith: { productTokens: ["3.5mm", "aux", "wired", "ath-m50", "hd 600", "hd650"] },
    why: "OFC braided cable with metal connectors — better longevity than stock rubber cables.",
  },
  {
    name: "USB-C to 3.5mm Aux Adapter (DAC)",
    brand: "Apple",
    price: 9.00,
    category: "headphones",
    accessoryKind: "accessory/adapter",
    url: null,
    specs: { quality: 0.75, price_score: 0.95, longevity: 0.55 },
    compatibleWith: {},
    why: "Active DAC handles 24-bit / 48kHz; small enough to live on the cable.",
  },
  {
    name: "Headphone Cleaning Kit",
    brand: "3D-Cosmos",
    price: 11.99,
    category: "headphones",
    accessoryKind: "accessory/cleaning-kit",
    url: null,
    specs: { quality: 0.60, price_score: 0.85, longevity: 0.40 },
    compatibleWith: {},
    why: "Soft brushes + microfiber + safe cleaning solution for ear pads and grills.",
  },
];

const COFFEE_MAKER: AccessoryFixture[] = [
  {
    name: "Descaler Tablets (6-count)",
    brand: "Urnex Dezcal",
    price: 10.99,
    category: "coffee-makers",
    accessoryKind: "accessory/descaler",
    url: null,
    specs: { quality: 0.75, price_score: 0.90, longevity: 0.50 },
    compatibleWith: {},
    why: "Citric + sulfamic blend safe for drip brewers, Keurigs, and most espresso machines.",
  },
  {
    name: "Keurig Water Filter Cartridges (6-pack)",
    brand: "K&J",
    price: 8.99,
    category: "coffee-makers",
    accessoryKind: "accessory/water-filter",
    url: null,
    specs: { quality: 0.70, price_score: 0.95, longevity: 0.35 },
    compatibleWith: { brands: ["Keurig"] },
    why: "OEM-compatible charcoal filters; replace every 2 months or 60 tank fills.",
  },
  {
    name: "Replacement 12-Cup Carafe",
    brand: "Cuisinart",
    price: 24.95,
    category: "coffee-makers",
    accessoryKind: "accessory/carafe",
    url: null,
    specs: { quality: 0.80, price_score: 0.65, longevity: 0.80 },
    compatibleWith: { brands: ["Cuisinart"] },
    why: "Direct OEM replacement — fits any 12-cup Cuisinart drip brewer.",
  },
  {
    name: "Chemex Filter Pack (100)",
    brand: "Chemex",
    price: 14.95,
    category: "coffee-makers",
    accessoryKind: "accessory/filter",
    url: null,
    specs: { quality: 0.90, price_score: 0.80, longevity: 0.40 },
    compatibleWith: { productTokens: ["chemex", "pourover"] },
    why: "Bonded paper retains oils + grounds, giving the clean Chemex cup profile.",
  },
  {
    name: "Stainless Coffee Scoop",
    brand: "OXO",
    price: 7.99,
    category: "coffee-makers",
    accessoryKind: "accessory/scoop",
    url: null,
    specs: { quality: 0.70, price_score: 0.90, longevity: 0.95 },
    compatibleWith: {},
    why: "2-tablespoon capacity with clip-on handle; dishwasher-safe.",
  },
];

export const ACCESSORY_CATALOG: Record<string, AccessoryFixture[]> = {
  "espresso-machines": ESPRESSO,
  laptops: LAPTOP,
  headphones: HEADPHONES,
  "coffee-makers": COFFEE_MAKER,
};

/** 54mm-portafilter brand family (Breville Bambino/Barista, De'Longhi, Gaggia Classic Pro). */
export const FAMILY_54MM = new Set(["breville", "de'longhi", "delonghi", "gaggia"]);
/** 58mm-portafilter brand family (commercial standard — Rancilio, Rocket, La Marzocco, Profitec, ECM). */
export const FAMILY_58MM = new Set(["rancilio", "rocket", "la marzocco", "profitec", "ecm"]);
