import type { Candidate } from "@lens/shared";

/**
 * Deterministic catalog used when LENS_SEARCH_MODE=fixture.
 *
 * Handcrafted for the submission demo — five categories matching the committed pitch.
 * Real-world product specs, representative but not exhaustive. Fictional "Presswell"
 * brand is the spec-optimal optimal machine that demonstrates the gap the demo exposes.
 *
 * Every product has:
 *   - name, brand, price (USD), url, thumbnailUrl
 *   - specs {} keyed to common criterion names the extractor produces
 *   - specs values are raw numbers where possible (so rank.ts normalizes correctly),
 *     or strings for text attributes
 *
 * NOTE: attributeScores / utilityScore / utilityBreakdown are populated by rank.ts.
 */

const ESPRESSO_MACHINES: Candidate[] = [
  {
    name: "Stilosa EC260BK",
    brand: "De'Longhi",
    price: 119,
    currency: "USD",
    url: "https://www.delonghi.com/en-us/stilosa-ec260bk",
    specs: {
      pressure: 15, // bar
      build: "plastic housing, stainless boiler", // mostly plastic
      build_score: 0.35,
      steam: "manual steam wand",
      steam_score: 0.4,
      weight_lbs: 8.1,
      water_tank_oz: 35,
      warranty_years: 1,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Bambino Plus BES500BSS",
    brand: "Breville",
    price: 499,
    currency: "USD",
    url: "https://www.breville.com/us/en/products/espresso/bes500.html",
    specs: {
      pressure: 19,
      build: "full stainless steel, brushed",
      build_score: 0.82,
      steam: "automatic steam wand with microfoam",
      steam_score: 0.85,
      weight_lbs: 11.5,
      water_tank_oz: 64,
      warranty_years: 2,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Artisan P20",
    brand: "Presswell",
    price: 389,
    currency: "USD",
    url: "https://www.presswell.example/artisan-p20",
    specs: {
      pressure: 20,
      build: "full stainless steel + brass boiler",
      build_score: 0.92,
      steam: "professional commercial-style steam wand",
      steam_score: 0.9,
      weight_lbs: 12.4,
      water_tank_oz: 70,
      warranty_years: 3,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Classic Evo Pro",
    brand: "Gaggia",
    price: 449,
    currency: "USD",
    url: "https://www.gaggia.com/classic-evo-pro",
    specs: {
      pressure: 15,
      build: "full stainless steel",
      build_score: 0.78,
      steam: "professional-style commercial steam wand",
      steam_score: 0.82,
      weight_lbs: 17.5,
      water_tank_oz: 72,
      warranty_years: 2,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Dedica Arte EC885",
    brand: "De'Longhi",
    price: 249,
    currency: "USD",
    url: "https://www.delonghi.com/en-us/dedica-arte-ec885",
    specs: {
      pressure: 15,
      build: "brushed stainless steel",
      build_score: 0.58,
      steam: "manual steam wand with enhanced cappuccino attachment",
      steam_score: 0.55,
      weight_lbs: 9.3,
      water_tank_oz: 35,
      warranty_years: 2,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
];

const LAPTOPS: Candidate[] = [
  {
    name: "ThinkPad E14 Gen 5",
    brand: "Lenovo",
    price: 749,
    currency: "USD",
    url: "https://www.lenovo.com/us/en/p/laptops/thinkpad/thinkpad-e-series/e14-gen-5",
    specs: {
      cpu: "AMD Ryzen 5 7530U",
      ram: 8,
      storage: 256,
      display: "14-inch FHD IPS",
      battery_hours: 10,
      weight_lbs: 3.5,
      keyboard_score: 0.95,
      reliability_score: 0.88,
      warranty_years: 1,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Framework Laptop 13 (AMD)",
    brand: "Framework",
    price: 999,
    currency: "USD",
    url: "https://frame.work/products/laptop-13-diy-amd",
    specs: {
      cpu: "AMD Ryzen 7 7840U",
      ram: 16,
      storage: 512,
      display: "13.5-inch 2256x1504 matte",
      battery_hours: 9,
      weight_lbs: 2.87,
      keyboard_score: 0.78,
      reliability_score: 0.82,
      warranty_years: 1,
      modular: true,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "MacBook Air M2",
    brand: "Apple",
    price: 999,
    currency: "USD",
    url: "https://www.apple.com/shop/buy-mac/macbook-air/13-inch-m2",
    specs: {
      cpu: "Apple M2",
      ram: 8,
      storage: 256,
      display: "13.6-inch Liquid Retina",
      battery_hours: 18,
      weight_lbs: 2.7,
      keyboard_score: 0.86,
      reliability_score: 0.9,
      warranty_years: 1,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Zenbook 14 OLED UX3405",
    brand: "ASUS",
    price: 899,
    currency: "USD",
    url: "https://www.asus.com/laptops/for-home/zenbook/zenbook-14-oled-ux3405/",
    specs: {
      cpu: "Intel Core Ultra 7 155H",
      ram: 16,
      storage: 1024,
      display: "14-inch 3K OLED",
      battery_hours: 14,
      weight_lbs: 2.82,
      keyboard_score: 0.8,
      reliability_score: 0.76,
      warranty_years: 1,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Pavilion 15-eg3053cl",
    brand: "HP",
    price: 799,
    currency: "USD",
    url: "https://www.hp.com/us-en/shop/pdp/hp-pavilion-laptop-15-eg3053cl",
    specs: {
      cpu: "Intel Core i5-1335U",
      ram: 16,
      storage: 512,
      display: "15.6-inch FHD",
      battery_hours: 7,
      weight_lbs: 3.86,
      keyboard_score: 0.7,
      reliability_score: 0.72,
      warranty_years: 1,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
];

const HEADPHONES: Candidate[] = [
  {
    name: "WH-1000XM5",
    brand: "Sony",
    price: 299,
    currency: "USD",
    url: "https://www.sony.com/electronics/headband-headphones/wh-1000xm5",
    specs: {
      anc_score: 0.96,
      battery_hours_anc_on: 30,
      battery_hours_anc_off: 40,
      weight_g: 250,
      comfort_score: 0.88,
      mic_score: 0.82,
      codec_support: "LDAC, AAC, SBC",
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Momentum 4 Wireless",
    brand: "Sennheiser",
    price: 279,
    currency: "USD",
    url: "https://www.sennheiser-hearing.com/en-US/p/momentum-4-wireless/",
    specs: {
      anc_score: 0.85,
      battery_hours_anc_on: 60,
      battery_hours_anc_off: 60,
      weight_g: 293,
      comfort_score: 0.92,
      mic_score: 0.78,
      codec_support: "aptX Adaptive, AAC, SBC",
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "QuietComfort Ultra",
    brand: "Bose",
    price: 299,
    currency: "USD",
    url: "https://www.bose.com/p/headphones/bose-quietcomfort-ultra-headphones",
    specs: {
      anc_score: 0.94,
      battery_hours_anc_on: 24,
      battery_hours_anc_off: 24,
      weight_g: 254,
      comfort_score: 0.94,
      mic_score: 0.8,
      codec_support: "aptX Adaptive, AAC, SBC",
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Elite 10 Gen 2",
    brand: "Jabra",
    price: 229,
    currency: "USD",
    url: "https://www.jabra.com/bluetooth-headphones/jabra-elite-10",
    specs: {
      anc_score: 0.78,
      battery_hours_anc_on: 27,
      battery_hours_anc_off: 36,
      weight_g: 249,
      comfort_score: 0.82,
      mic_score: 0.88,
      codec_support: "LE Audio, AAC, SBC",
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Px7 S2e",
    brand: "Bowers & Wilkins",
    price: 249,
    currency: "USD",
    url: "https://www.bowerswilkins.com/en-us/product/headphones/px7s2e/",
    specs: {
      anc_score: 0.82,
      battery_hours_anc_on: 30,
      battery_hours_anc_off: 30,
      weight_g: 307,
      comfort_score: 0.84,
      mic_score: 0.74,
      codec_support: "aptX Adaptive, AAC, SBC",
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
];

const COFFEE_MAKERS: Candidate[] = [
  {
    name: "KF85 Brew ID",
    brand: "Technivorm",
    price: 369,
    currency: "USD",
    url: "https://www.technivorm.com/product/moccamaster-kf85/",
    specs: {
      brew_time_minutes: 6,
      brew_temp_f: 200,
      capacity_cups: 10,
      sca_certified: true,
      build_score: 0.9,
      ease_score: 0.78,
      warranty_years: 5,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Brew Precision",
    brand: "OXO",
    price: 199,
    currency: "USD",
    url: "https://www.oxo.com/brew-precision-coffee-maker",
    specs: {
      brew_time_minutes: 7,
      brew_temp_f: 198,
      capacity_cups: 9,
      sca_certified: true,
      build_score: 0.72,
      ease_score: 0.9,
      warranty_years: 2,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Specialty Coffee Maker",
    brand: "Breville",
    price: 349,
    currency: "USD",
    url: "https://www.breville.com/us/en/products/coffee/bdc450.html",
    specs: {
      brew_time_minutes: 6,
      brew_temp_f: 201,
      capacity_cups: 12,
      sca_certified: true,
      build_score: 0.85,
      ease_score: 0.86,
      warranty_years: 2,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Specialty Drip",
    brand: "Ratio",
    price: 429,
    currency: "USD",
    url: "https://www.ratiocoffee.com/products/ratio-eight",
    specs: {
      brew_time_minutes: 6,
      brew_temp_f: 199,
      capacity_cups: 8,
      sca_certified: true,
      build_score: 0.94,
      ease_score: 0.82,
      warranty_years: 3,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "12-Cup Programmable",
    brand: "Cuisinart",
    price: 99,
    currency: "USD",
    url: "https://www.cuisinart.com/coffee-makers/12-cup-programmable",
    specs: {
      brew_time_minutes: 8,
      brew_temp_f: 195,
      capacity_cups: 12,
      sca_certified: false,
      build_score: 0.55,
      ease_score: 0.8,
      warranty_years: 3,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
];

const VACUUMS: Candidate[] = [
  {
    name: "Roborock S8 Pro Ultra",
    brand: "Roborock",
    price: 1599,
    currency: "USD",
    url: "https://us.roborock.com/pages/roborock-s8-pro-ultra",
    specs: {
      suction_pa: 6000,
      mop: true,
      auto_empty: true,
      mapping_score: 0.94,
      noise_db: 64,
      battery_minutes: 180,
      warranty_years: 1,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Roomba j9+",
    brand: "iRobot",
    price: 899,
    currency: "USD",
    url: "https://www.irobot.com/en_US/roomba-j9-plus-robot-vacuum/j9-plus.html",
    specs: {
      suction_pa: 2500,
      mop: false,
      auto_empty: true,
      mapping_score: 0.88,
      noise_db: 62,
      battery_minutes: 180,
      warranty_years: 1,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Dreame L20 Ultra",
    brand: "Dreame",
    price: 1299,
    currency: "USD",
    url: "https://www.dreametech.com/products/l20-ultra",
    specs: {
      suction_pa: 7000,
      mop: true,
      auto_empty: true,
      mapping_score: 0.9,
      noise_db: 65,
      battery_minutes: 260,
      warranty_years: 2,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "Eufy X10 Pro Omni",
    brand: "Eufy",
    price: 799,
    currency: "USD",
    url: "https://us.eufy.com/products/t2351",
    specs: {
      suction_pa: 8000,
      mop: true,
      auto_empty: true,
      mapping_score: 0.83,
      noise_db: 61,
      battery_minutes: 180,
      warranty_years: 1,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
  {
    name: "S7 MaxV Ultra",
    brand: "Roborock",
    price: 1199,
    currency: "USD",
    url: "https://us.roborock.com/pages/roborock-s7-maxv-ultra",
    specs: {
      suction_pa: 5100,
      mop: true,
      auto_empty: true,
      mapping_score: 0.92,
      noise_db: 67,
      battery_minutes: 180,
      warranty_years: 1,
    },
    attributeScores: {},
    utilityScore: 0,
    utilityBreakdown: [],
  },
];

const CATALOG: Record<string, Candidate[]> = {
  "espresso machine": ESPRESSO_MACHINES,
  espresso: ESPRESSO_MACHINES,
  laptop: LAPTOPS,
  laptops: LAPTOPS,
  headphones: HEADPHONES,
  "over-ear headphones": HEADPHONES,
  "coffee maker": COFFEE_MAKERS,
  "coffee makers": COFFEE_MAKERS,
  "drip coffee maker": COFFEE_MAKERS,
  vacuum: VACUUMS,
  vacuums: VACUUMS,
  "robot vacuum": VACUUMS,
  "robot vacuums": VACUUMS,
};

export function lookupCatalog(category: string): Candidate[] {
  const key = category.trim().toLowerCase();
  if (CATALOG[key]) return deepCopy(CATALOG[key]);
  // fuzzy: try contains
  for (const [k, v] of Object.entries(CATALOG)) {
    if (key.includes(k) || k.includes(key)) return deepCopy(v);
  }
  // default: return espresso so demos still produce something visible
  return deepCopy(ESPRESSO_MACHINES);
}

function deepCopy<T>(v: T): T {
  return JSON.parse(JSON.stringify(v));
}
